Repository WeMakeDevs/wemakedevs, pull requests merged in 2022-12, with the labels that each got.

#155 Bug-Fix: External link opening while clicking home
  src/v1/components/common/navbar/data.js
  src/v1/components/common/navbar/index.jsx
Labels: bug, contributor

#209 fix style issue in about us card
  src/components/home/about/index.module.css
Labels: contributor

#223 Fixed spacing in README above the image and made image clickable
  README.md
Labels: contributor

#227 Community links added in footer banner
  src/components/layout/Footer/index.jsx
Labels: contributor

#241 add join card and fixed gradient, testimonial card add background
  src/App.jsx
  src/components/home/JoinUs/index.jsx
  src/components/home/JoinUs/index.module.css
  src/components/home/Mentorship/index.jsx
  src/components/home/Partner/Gradient.png
  src/components/home/Partner/index.js
  src/components/home/Partner/index.jsx
  src/components/home/Partner/index.module.css
  src/components/home/Testimonial/index.jsx
  src/components/home/Testimonial/index.module.css
  src/components/home/about/cards.jsx
  src/components/home/about/index.jsx
  src/components/home/about/index.module.css
  src/components/home/courses/index.jsx
  src/components/home/events/index.jsx
  src/components/home/header/Header.png
  src/components/home/header/index.jsx
  src/components/home/header/index.module.css
  src/components/layout/Banner/index.jsx
  src/components/layout/Banner/index.module.css
  src/components/layout/ColumnSection/index.jsx
  src/components/layout/ColumnSection/index.module.css
  src/css/base/root.css
  src/css/utlities/gradient.css
  src/css/utlities/link-normal.css
  src/css/utlities/link-primary.css
  src/css/utlities/link-white.css
  src/index.css
  src/pages/HomePage.jsx
  src/styles/root.css
  src/styles/utils.css
Labels: team

#245 feat: stats, FAQ section
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/AccordionItem.jsx
  src/components/Accordion/index.css
  src/components/home/FAQ/data.js
  src/components/home/FAQ/index.jsx
  src/components/home/FAQ/index.module.css
  src/components/home/Stats/index.jsx
  src/components/home/Stats/index.module.css
  src/pages/HomePage.jsx
Labels: team

#248 [Feature]: Work Section
  src/assets/home/MorganStanley.svg
  src/assets/home/RedBus.svg
  src/assets/home/adobe.svg
  src/assets/home/amazon-2 (1).svg
  src/assets/home/amazon-2.svg
  src/assets/home/amazon-logo.svg
  src/assets/home/amazon.svg
  src/assets/home/google-logo.svg
  src/assets/home/google.svg
  src/assets/home/microsoft.svg
  src/assets/home/microsoft_logo.png
  src/components/home/Work/index.jsx
  src/components/home/Work/index.module.css
  src/pages/HomePage.jsx
Labels: team

#266 fixed inconsistent spacing between heading and content
  .husky/post-merge
  src/components/Accordion/index.css
  src/components/home/FAQ/index.module.css
  src/components/home/Partner/index.module.css
  src/components/home/Stats/index.module.css
  src/components/home/Testimonial/index.module.css
  src/components/layout/ColumnSection/index.module.css
Labels: team

#273 feat: footer with category links
  src/components/home/FAQ/index.jsx
  src/components/home/Testimonial/index.jsx
  src/components/layout/Footer/index.jsx
  src/components/layout/Footer/index.module.css
Labels: team
